defaults: &defaults
  working_directory: /go/src/github.com/segmentio/terrafile
  docker:
    - image: circleci/golang:1.12.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: build_and_test
          command: |
            GO111MODULE=on go build -v
            GO111MODULE=on go test -v
      - run:
          name: Check modules are tidy and checked in
          command: |
            export GO111MODULE=on
            go mod tidy
            go mod vendor
            if [ "$(git status --porcelain)" != "" ]; then
              echo "git tree is dirty after tidying and vendoring modules"
              echo "ensure go.mod and go.sum are tidy and vendor is checked in"
              git status
              exit 1
            fi

workflows:
  version: 2
  release:
    jobs:
      - build
